--1a. Pescatarian Diet Foods
SELECT *
FROM MACROS_TABLE
WHERE DIET_TYPE != 'Omnivorous'

--1b. Vegetarian Diet Foods
SELECT *
FROM MACROS_TABLE
WHERE DIET_TYPE = 'Vegetarian'
	OR DIET_TYPE = 'Vegan'

--1c. Vegan Diet Foods
SELECT *
FROM MACROS_TABLE
WHERE DIET_TYPE = 'Vegan'

--2a. Top Protein Foods for Omnivorous
SELECT *
FROM MACROS_TABLE
ORDER BY PROTEINS_100G DESC

--2b. Top Protein Foods for Vegetarians
SELECT *
FROM MACROS_TABLE
WHERE DIET_TYPE = 'Vegetarian'
	OR DIET_TYPE = 'Vegan'
ORDER BY PROTEINS_100G DESC

--2c. Top Protein Foods for Vegan
SELECT *
FROM MACROS_TABLE
WHERE DIET_TYPE = 'Vegan'
ORDER BY PROTEINS_100G DESC

--2d. Top Protein for Pescatarian
SELECT *
FROM MACROS_TABLE
WHERE DIET_TYPE != 'Omnivorous'
ORDER BY PROTEINS_100G DESC

--3a.
-- Diet avg of Veggie
SELECT AVG(PROTEINS_100G) AS AVG_PROTEIN_IN_DIET,
	AVG(FAT_100G) AS AVG_FATS_IN_DIET,
	AVG(CARBOHYDRATES_100G) AS AVG_CARBS_IN_DIET,
	AVG(ENERGY_100G) AS AVG_CALORIES_IN_DIET
FROM MACROS_TABLE
WHERE DIET_TYPE = 'Vegetarian'
	OR DIET_TYPE = 'Vegan'

--3b.
-- Diet avg of Vegan
SELECT AVG(PROTEINS_100G) AS AVG_PROTEIN_IN_DIET,
	AVG(FAT_100G) AS AVG_FATS_IN_DIET,
	AVG(CARBOHYDRATES_100G) AS AVG_CARBS_IN_DIET,
	AVG(ENERGY_100G) AS AVG_CALORIES_IN_DIET
FROM MACROS_TABLE
WHERE DIET_TYPE = 'Vegan'

--3c.
-- Diet avg of Pescatarian
SELECT AVG(PROTEINS_100G) AS AVG_PROTEIN_IN_DIET,
	AVG(FAT_100G) AS AVG_FATS_IN_DIET,
	AVG(CARBOHYDRATES_100G) AS AVG_CARBS_IN_DIET,
	AVG(ENERGY_100G) AS AVG_CALORIES_IN_DIET
FROM MACROS_TABLE
WHERE DIET_TYPE != 'Omnivorous'

--3d.
--Diet avg of all foods
SELECT AVG(PROTEINS_100G) AS AVG_PROTEIN_IN_DIET,
	AVG(FAT_100G) AS AVG_FATS_IN_DIET,
	AVG(CARBOHYDRATES_100G) AS AVG_CARBS_IN_DIET,
	AVG(ENERGY_100G) AS AVG_CALORIES_IN_DIET
FROM MACROS_TABLE

--4.
-- Percent_energy of all foods and Omnivorous
SELECT FOOD_NAME,
	(PROTEINS_100G / ENERGY_100G) AS PERCENT_ENERGY
FROM MACROS_TABLE
ORDER BY PERCENT_ENERGY DESC

--5.
-- Food with most carbs
SELECT FOOD_NAME,
	CARBOHYDRATES_100G
FROM MACROS_TABLE
ORDER BY CARBOHYDRATES_100G DESC

--6.
-- Food with most Fat
SELECT FOOD_NAME,
	FAT_100G
FROM MACROS_TABLE
ORDER BY FAT_100G DESC

--7.
--Macros of each food Group
SELECT CATEGORY_NAME,
	AVG(PROTEINS_100G) AS AVG_PROTEIN_IN_DIET,
	AVG(FAT_100G) AS AVG_FATS_IN_DIET,
	AVG(CARBOHYDRATES_100G) AS AVG_CARBS_IN_DIET,
	AVG(ENERGY_100G) AS AVG_CALORIES_IN_DIET
FROM MACROS_TABLE
GROUP BY CATEGORY_NAME

--8.
-- Food group with the highest Calories
SELECT CATEGORY_NAME,
	AVG(ENERGY_100G) AS AVG_CALORIES_PER_100G
FROM MACROS_TABLE
GROUP BY CATEGORY_NAME
ORDER BY AVG_CALORIES_PER_100G DESC

--9.
-- Food group with highest Protein
SELECT CATEGORY_NAME,
	AVG(PROTEINS_100G) AS AVG_PROTEINS_PER_100G
FROM MACROS_TABLE
GROUP BY CATEGORY_NAME
ORDER BY AVG_PROTEINS_PER_100G DESC